<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="OpenConquer.Content.Tool.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/OpenConquer.Content/OpenConquer.Content.csproj" />
  </ItemGroup>

</Project>
