version: 2

updates:
  - package-ecosystem: nuget
    directory: '/'
    schedule:
      interval: weekly
    groups:
      silk-net:
        patterns:
          - 'Silk.NET.*'

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
