using OpenConquer.Rendering.Presentation;

namespace OpenConquer.Client.UI.Hud;

internal readonly record struct MainHudStatusHintRectangle(int X, int Y, int Width, int Height)
{
    public bool Contains(int x, int y)
    {
        return x >= X && y >= Y && x < (long)X + Width && y < (long)Y + Height;
    }
}

internal readonly record struct MainHudStatusHintAnchor(int X, int Y);

internal readonly record struct MainHudStatusHintLayout
{
    private readonly int _logicalWidth;
    private readonly int _dialogOriginY;

    private MainHudStatusHintLayout(int logicalWidth, int dialogOriginY)
    {
        _logicalWidth = logicalWidth;
        _dialogOriginY = dialogOriginY;
    }

    public static MainHudStatusHintLayout Create(LogicalRenderSize logicalRenderSize)
    {
        bool supported = logicalRenderSize is { Width: 800, Height: 600 } or { Width: 1024, Height: 768 };

        if (!supported)
        {
            throw new ArgumentOutOfRangeException(nameof(logicalRenderSize), logicalRenderSize, "Native 5517 main HUD status-hint geometry is verified only at 800x600 and 1024x768.");
        }

        return new MainHudStatusHintLayout(logicalRenderSize.Width, logicalRenderSize.Height - MainHudStatusHintDefinition.MainDialogHeight);
    }

    public int LogicalWidth => _logicalWidth;
    public int DialogOriginY => _dialogOriginY;

    public (int X, int Y) ToDialogLocal(int logicalX, int logicalY) => (logicalX, logicalY - _dialogOriginY);

    public int GetRegionX(int localX, bool alternateLayout) => alternateLayout ? _logicalWidth - localX : localX;

    public static MainHudStatusHintRectangle GetRectangle(int hotspot)
    {
        return hotspot switch
        {
            0 => new MainHudStatusHintRectangle(99, 95, 398, 12),
            1 => new MainHudStatusHintRectangle(0, 23, 22, 22),
            2 => new MainHudStatusHintRectangle(0, 0, 0, 0),
            3 => new MainHudStatusHintRectangle(72, 23, 22, 22),
            4 => new MainHudStatusHintRectangle(50, 11, 22, 22),
            5 => new MainHudStatusHintRectangle(22, 11, 22, 22),
            _ => throw new ArgumentOutOfRangeException(nameof(hotspot), hotspot, "Hotspot is not a native rectangular control."),
        };
    }

    public MainHudStatusHintAnchor GetAnchor(MainHudStatusHintKind kind)
    {
        (int x, int y) = kind switch
        {
            MainHudStatusHintKind.None => (99, 97),
            MainHudStatusHintKind.WalkRun => (0, 23),
            MainHudStatusHintKind.Map => (72, 23),
            MainHudStatusHintKind.ScreenShift => (50, 11),
            MainHudStatusHintKind.Equipment => (22, 11),
            MainHudStatusHintKind.Skill => (0, 50),
            MainHudStatusHintKind.Mana => (52, 54),
            MainHudStatusHintKind.Life => (4, 54),
            MainHudStatusHintKind.Chat => throw new InvalidOperationException("The hidden chat control's anchor depends on the native dialog font and is not generated by the main-HUD hotspot producer."),
            _ => throw new ArgumentOutOfRangeException(nameof(kind), kind, "Unknown native main HUD status-hint kind."),
        };

        return new MainHudStatusHintAnchor(x, _dialogOriginY + y + MainHudStatusHintDefinition.AnchorOffsetY);
    }

    public static MainHudStatusHintRectangle GetChatControlRectangle(int dialogBaseUnitX, int dialogBaseUnitY)
    {
        ArgumentOutOfRangeException.ThrowIfNegativeOrZero(dialogBaseUnitX);
        ArgumentOutOfRangeException.ThrowIfNegativeOrZero(dialogBaseUnitY);

        return new MainHudStatusHintRectangle(
            MulDiv(35, dialogBaseUnitX, 4),
            MulDiv(16, dialogBaseUnitY, 8),
            MulDiv(11, dialogBaseUnitX, 4),
            MulDiv(11, dialogBaseUnitY, 8));
    }

    private static int MulDiv(int value, int multiplier, int divisor)
    {
        long product = checked((long)value * multiplier);
        return checked((int)((product + divisor / 2) / divisor));
    }
}
