<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenConquer.Gameplay\OpenConquer.Gameplay.csproj" />
    <ProjectReference Include="..\OpenConquer.Rendering\OpenConquer.Rendering.csproj" />
    <ProjectReference Include="..\OpenConquer.Content\OpenConquer.Content.csproj" />
    <ProjectReference Include="..\OpenConquer.Networking\OpenConquer.Networking.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.Input" />
    <PackageReference Include="Silk.NET.Windowing" />
  </ItemGroup>

</Project>
