[ExpShowPos]
Exp_XPos=485
Exp_YPos=675
AddExp_XPos=575
AddExp_YPos=675

Exp_XPos_800X600=485
Exp_YPos_800X600=510
AddExp_XPos_800X600=575
AddExp_YPos_800X600=510

[FontSize]
Size=12
Width=6

//经验条配置
[FontSize2]
Size=15
Width=6

[ChatFontSize] //聊天框字体大小
size=12

// 装备追加界面
[EquipAppend]
PrgInterval=2     // 间隔，指每隔多少个循环才执行一次进度条动画
PrgStep=30     // 表示进度条每次走1/10
RateInfo_X=118
RateInfo_Y=140

// 图片数目
[AntiFraud]
PicCount=1

// VIP特权论坛地址的地方
[HttpLink]
Forum=http://bbs.co.91.com/

// VIP界面
[VipDepot]
VIPTIP_X=155
VIPTIP_Y=220

//开洞界面数字起始位置
[OPENHOLE]
DIGIT_X=30
DIGIT_Y=105

// 查看花束排行榜对话框底框图显示的偏移量
[DlgFlowerRank]
Pic_OffsetX=-59
Pic_OffsetY=-83

// 接受花束对话框底框图显示的偏移量
[DlgGetFlower]
Pic_OffsetX=-74
Pic_OffsetY=-93

//启动界面
[DlgLogo]
BgFormat=Data/Main/Logo%d.bmp

[Language]
StringFile=ini\cn_Res.ini

//忍法杀阵;透明度; 混合贴图编号，索引3DTexture.ini
[KOImage]
Alpha=90
Texture=999000000

//忍者替身术-高度偏移配置
[Scapegoat]
OffsetY=100

[Quiz]
// 系统消息/状态图标在题目面板完全展开时比之正常状态的偏移值
LeftScaleY=105
// ;小地图/小地图按钮在题目面板完全展开时比之正常状态的偏移值
RightScaleY=137
// 自动寻路按钮在正常状态下的Y值
AutoRunBtnY=140
// 自动寻路对话框在正常状态下的Y值
AutoRunDlgY=179

//智力竞赛搜索
[QuizSearch]
Url=www.google.com/search?q=

//卡片系统
[DlgCard]
x=153
y=28
w=408
h=280
StaticBG=HotkeySetSelect

//卡片出生时出生光效的播放时间
[Card]
timeInteravl=2000

//在登陆界面输入帐号密码后按键盘上的回车键无法正常进入.
//[LoginFlash]
//BtnEnterOffsetX=742
//BtnEnterOffsetY=710

//表示任务完成时显示任务名的颜色
[DlgMissionSystem]
TaskFinishColor=0xffff0000

//表示任务完成时显示任务名的颜色
[MissionSystem]
TaskFinishColor=0xff00CD00
TreeHeight=192
TreeFont=Courier New
TreeFontSize=12
//任务名称颜色
TaskNameColor=0xffCFC058
TaskNameFront=Courier New
//任务名称字体宽
TaskNameWidth=6
//任务名称字体高
TaskNameHeight=12
//任务描述颜色
TaskDescribeColor=0xffFFFFFF
TaskDescribeFront=Courier New
TaskDescribeWidth=6
TaskDescribeHeight=12
//任务目标颜色
TaskTargetColor=0xffFFFFFF
TaskTargetFront=Courier New
TaskTargetWidth=6
TaskTargetHeight=12
//任务奖励颜色
TaskAwardColor=0xffFFFFFF
TaskAwardFront=Courier New
TaskAwardWidth=6
TaskAwardHeight=12

//独立聊天主界面人物头像位置和方向
[ChatFace]
FaceW=32
OffsetX=3
SepX=32

//任务对话框选项、人物头像显示位置
[TaskDlg]
OddX=22
EvenX=282
FaceX=10
TextX=84

//自动寻路对话框位置、弹出方向、二级菜单位置、Tip位置及长度
[AutoRunDlg]
SubMenuMainMenuOffsetX=-170
MenuTextX=31
MenuW=190
// 自动寻路Tip每行显示字符数, 简体中文版本，繁体中文版本，日文版本
TipCharPerLineShort=22
// 自动寻路Tip每行显示字符数, 英文版本，法文版本，西班牙文版本
TipCharPerLineWide=50

[MainDlgRgnChg]
; 主对话框上凸一块相对于主对话框位置
x=0
y=0
w=90
h=90

//小地图附近地图名称显示位置
[RegionName]
;地图名称显示位置与屏幕边缘的间隔
EdgeDis=100

//个配置为帮派成员信息显示时第二列的起始位置(相对于对话框)
[DlgQuery_Faction]
listColOffsetX=130

//留言板点击输入后光标显示
[DlgEffigy]
DummyOffsetX=130

//支持错误日志上传
[DumpError]
Enable=1
Server=haha.91.com
Action=enzferrormsg/msg.php
Client=zf

//系统消息位置
[MsgPrefix]
// 根据不同语言版本进行设置，
MsgPrefixWidth=50

//马匹合成对话框1024(上)
[MountAppend]
DummyScale=50
DummyOffsetX=55
DummyOffsetY=95
DummyRotateX=0
DummyRotateY=0
DummyRotateZ=-90
MovieBgOffsetX=15
MovieBgOffsetY=-45
MovieBgW=930
MovieBgH=830
MovieBegin=500
MovieEnd=10500
BorderOffsetX=2
BorderOffsetY=2
BgEffectBegin=0
BgEffectEnd=11000

//马匹合成对话框1024(下)
[MountAppendConfirm]
DummyScale=50
DummyOffsetX=55
DummyOffsetY=95
DummyRotateX=0
DummyRotateY=0
DummyRotateZ=-90

//马匹合成对话框800(上)
[MountAppend800X600]
DummyScale=50
DummyOffsetX=55
DummyOffsetY=95
DummyRotateX=0
DummyRotateY=0
DummyRotateZ=-90
MovieBgOffsetX=15
MovieBgOffsetY=0
MovieBgW=730
MovieBgH=630
MovieBegin=500
MovieEnd=11000
BorderOffsetX=2
BorderOffsetY=2
BgEffectBegin=0
BgEffectEnd=11000

//马匹合成对话框800(下)
[MountAppendConfirm800X600]
DummyScale=50
DummyOffsetX=55
DummyOffsetY=95
DummyRotateX=0
DummyRotateY=0
DummyRotateZ=-90

[FamilyInfo]
MapID=1002
NPCID=5533
NPCX=406
NPCY=390
Radius=4
EditPlaPositionX=100

[DlgFamConfirm]
SBtnConfirmWidth=38
LBtnConfirmWidth=60
SBtnCancelWidth=38
LBtnCancelWidth=60
BtnConfirm-Dialog15-X=60
BtnConfirm-Dialog15-Y=80
BtnConfirm-Family_AddRivalryBG-X=45
BtnConfirm-Family_AddRivalryBG-Y=123
BtnConfirm-Family_DonationBG-X=30
BtnConfirm-Family_DonationBG-Y=80
BtnCancel-Dialog15-X=145
BtnCancel-Dialog15-Y=80
BtnCancel-Family_AddRivalryBG-X=135
BtnCancel-Family_AddRivalryBG-Y=123
BtnCancel-Family_DonationBG-X=110
BtnCancel-Family_DonationBG-Y=80

//配置骑宠合成对话框的物品Tip显示相对物品显示的位置，若无配置，默认值是 200和0
[TipOffset]
MountAppendOffsetX=200
MountAppendOffsetY=0

//威吓技能冷却时间倒计时显示用的
[Magic]
TimeOffsetX=0
TimeOffsetY=0
FontSize=20

//表示追踪任务面板字体和颜色
[DlgTaskTrace]
Font=Courier New
FontSize=13

//全服邀请倒计时光效位置
[dlgconfirm]
actioncountdownposx=100
actioncountdownposy=100

[DlgTotemTotal]
// 前五战斗力颜色
BpColor0=
BpColor1=
BpColor2=
BpColor3=
BpColor4=
// 悬浮提示文字相对控件的位置
TipOffsetX=38
TipOffsetY=0
// 小极品图标显示偏移及缩放
NonsuchOffsetX=40
NonsuchOffsetY=40
NonsuchW=
NonsuchH=

[DlgTotemDetail]
// 自己的装备与他人装备的颜色
MyEqColor=0xCFC058
NormalEqColor=0xffFFFFFF
// 等级数字图片间的间隔
DigitSepX=8
// 悬浮提示文字相对控件的位置
FocusOffsetX=0
FocusOffsetY=0
// 小极品图标显示偏移及缩放
NonsuchOffsetX=40
NonsuchOffsetY=40
NonsuchW=
NonsuchH=

//帮派册封界面
[SynAppoint]
//选中条起始位置
OffSetX=10
OffSetY=25
//选中条偏移高度
offSetHeight=48
//选中条的长宽
BgWidth=245
BgHeight=85
SelectWidth=135
SelectHeight=67

[PuzzleBmp]
FrameIntervalMilliSec=100

//手机购买网页
[Phone_Buy_Web]
x=20
y=40
w=370
h=410

[ItemActive]
//物品未激活提示颜色
NormalColor=0xffCFC058
//物品激活提示颜色
ActiveColor=0xffff0000

//德州扑克配置
[SHMgr]
ClearBuf4Role=0

//物品固化
[Solidify]
EquipmentOffsetX=-10   // 表示tip提示（“请放入固化物”这样的提示）相对于装备栏和格子的偏移，左上角为0,0    (注释不要写入配置文件)
EquipmentOffsetY=-8
EquipmentTipWidth=65
SolidifyTipWidth=200
SolidifyOffsetX=10
SolidifyOffsetY=-17
FontColor=0xff00ff00  // 表示tip提示的字体颜色
BgColor=0x00ffffff     // 表示tip提示的背景颜色
lev1=10    // 表示淬炼状态等级固化所需要的能量 (固化1级淬炼状态 需要固化能量10)
lev2=30
lev3=70
lev4=150
lev5=270

//物品的tip
[DlgItemTip]
amount=74
attr1=shadiness
attr2=name
attr3=origintype
attr4=itemtype
attr5=mount
attr6=pro
attr7=weapon_skill
attr8=lev
attr9=magic_penetrate
attr10=sex
attr11=force
attr12=speed
attr13=health
attr14=soul
attr15=attack
attr16=defense
attr17=magic_attack
attr18=magic_defense
attr19=shield_block
attr20=dexterity
attr21=dodge
attr22=left_time
attr23=solidify
attr24=life
attr25=attr_metal
attr26=attr_wood
attr27=attr_water
attr28=attr_fire
attr29=attr_earth
attr30=critical_rate
attr31=magic_critical_rate
attr32=anti_magic_critical_rate
attr33=mana
attr34=mountspeed
attr35=dexterity_plus
attr36=dodge_plus
attr37=attack_plus
attr38=defense_plus
attr39=magic_attack_plus
attr40=magic_defense_plus
attr41=crash_attack
attr42=crash_defense
attr43=life_plus
attr44=mount_speed_plus
attr45=gem
attr46=open_hole_process
attr47=recover_delay
attr48=weight
attr49=loss
attr50=add_exp
attr51=bind
attr52=reduce_damage
attr53=add_life
attr54=anti_monster
attr55=max_overlay
attr56=sell_price
attr57=repair_price
attr58=honor
attr59=race_point
attr60=hide
attr61=fuse
attr62=target_monster
attr63=killed
attr64=kill_task
attr65=low_level_god_equip
attr66=recover_energy
attr67=desc
attr68=Broken
attr69=trainer_lev
attr70=unbind
attr71=monopoly
attr72=appen_fail
attr73=time
attr74=god_equip_left_time

//外置聊天界面关闭按钮闪光提示，聊天泡泡提示
[OUTCHAT]
CloseEffect=chatclosebtn
MinWidth1024=160
MinHeight1024=120
MaxWidth1024=1024
MaxHeight1024=788
MinWidth800=160
MinHeight800=120
MaxWidth800=800
MaxHeight800=600

//大号字体配置
[BigFontSize]
Size=19
Width=10

// 这是用来配置弓箭手剩余箭支数目以及箭袋图片位置的，现在血槽旁的天石商店按钮会挡住箭袋，只能显示出一个数字，建议修改显示坐标)
[ArrowShowOffset]
OffsetX=135
OffsetY=126
// 以下两个用于配置叠加数字显示在grid（如，物品背包），或image（如，人物装备）的什么位置以及数字大小
// Dir:0 1 2 3分别对应左上角、左下角、右上角、右下角
// Size:16就是图片本身原始大小，增减可放大缩小数字
[GridNum]
Dir=3
Size=16
[ImageNum]
Dir=3
Size=16

//伴随有时间条的探索动作执行
[LastingAction]
;底图偏移
ProOffsetX=4
ProOffsetY=4
;发光边缘偏移
MovOffsetX=-5
; 1024×768模式的位置和大小
x=470
y=580
w=193
h=16
; 800×600模式的位置和大小
x800X600=350
y800X600=430
w800X600=182
h800X600=16
; 字号
FontSize=16

//用于配置字体 文字y坐标位置， 字体大小，  字体颜色
[ReturnTime]
PosY=120
FontSize=20
FontColor=0xffff0000

//人物属性对话框的间距
[DlgHeroAttri]
SpaceBetween=13

[DlgPlayerAttri]
SpaceBetween=13

//神魂永久固化
[NonsuchSolidify]
EquipmentOffsetX=0   // 表示tip提示（“请放入固化物”这样的提示）相对于装备栏和格子的偏移，左上角为0,0
EquipmentOffsetY=-8
EquipmentTipWidth=65
SolidifyTipWidth=200
SolidifyOffsetX=10
SolidifyOffsetY=-2
FontColor=0xff00ff00  // 表示tip提示的字体颜色
BgColor=0x00ffffff     // 表示tip提示的背景颜色

[DlgSubProDetail]
StepImageOffsetX=20
StepImageOffsetyY=7
DivImageOffSetY=15

[DlgSubProConfirm]
//就职地图ID
AccessionMapID=1004
//就职NPC
AccessionNpcID=7775
//就职地图X轴坐标
AccessionPosX=65
//就职地图Y轴坐标
AccessionPosY=57
//晋阶地图ID
StepUpMapID=1004
//晋阶NPC
StepUpNpcID=1002
//晋阶地图X轴坐标
StepUpPosX=64
//晋阶地图Y轴坐标
StepUpPosY=49
BtnOKSetOffY=-30
BtnCancelSetOffY=-30

//副职业界面人物显示
[DlgSubProfession]
DummyOffsetX=310
DummyOffsetY=270
IconOffsetX=150
IconOffsetY=1

//人物属性对话框的间距
[DlgHeroAttri]
SpaceBetween=13

[DlgPlayerAttri]
SpaceBetween=13

// 神器锻造界面数据
[DlgUpgrade2Nonsuch]
IntroFontHeight=12
IntroFontWidth=6

//火龙弹八方向的起点偏移
[MagicTraceOffsetX]
701700=-64
701701=-128
701702=-64
701703=0
701704=64
701705=128
701706=64
701707=0
1050400=-64
1050401=-128
1050402=-64
1050403=0
1050404=64
1050405=128
1050406=64
1050407=0
1036300=30
1036301=-50
1036302=0
1036303=0
1036304=50
1036305=20
1036306=20
1036307=0
[MagicTraceOffsetY]
701700=148
701701=100
701702=132
701703=164
701704=132
701705=100
701706=148
701707=164
1050400=148
1050401=100
1050402=132
1050403=164
1050404=132
1050405=100
1050406=148
1050407=164
1036300=5
1036301=80
1036302=70
1036303=20
1036304=50
1036305=70
1036306=100
1036307=150

//物品tips说明中支持取物品名称
[TIPSDESCCOLOR]
FontColor=0xff00ff00

[DailyActivity]
//活动名称颜色
ActivityNameColor=0xffffff00
//活动内容颜色
ActivityContentColor=0xffffffff
//面板文字宽度
ActivityWidth=6
ActivityHeight=13
//刷新活动时间间隔，秒为单位
FlashTime=60

[BossEffect]
; 底图在屏幕上的位置
BGX=0
BGY=525
; 底图索引ani
BGAni=Boss_ShowbossbBG
; 血条在屏幕上的位置
ShowX=17
ShowY=580
; 血条行间距
LineSep=20
; 血条行高
LineHeight=13
; 血条行宽
LinePixel=994
; 失血渐变速度
PixelStep=3
ColorAmount=20
Color0=0xFFFF0000
Color1=0xFFFFBFFF
Color2=0xFFFF9200
Color3=0xFFFFFF00
Color4=0xFF00FF00
Color5=0xFF21CDA0
Color6=0xFF00FFFF
Color7=0xFF0000FF
Color8=0xFFFA1BD0
Color9=0xFF7000FF
Color10=0xFF175B93
Color11=0xFF169F02
Color12=0xFFFF80FF
Color13=0xFFFF8080
Color14=0xFF808040
Color15=0xFFEA62C1
Color16=0xFF9D9DFF
Color17=0xFF808080
Color18=0xFFFF8040
Color19=0xFFAF0541

; 800X600模式下的配置
BGX800X600=0
BGY800X600=355
BGAni800X600=Boss_ShowbossbBG
ShowX800X600=17
ShowY800X600=410
LineSep800X600=20
LineHeight800X600=13
LinePixel800X600=770
PixelStep800X600=3
ColorAmount=20
Color0=0xFFFF0000
Color1=0xFFFFBFFF
Color2=0xFFFF9200
Color3=0xFFFFFF00
Color4=0xFF00FF00
Color5=0xFF21CDA0
Color6=0xFF00FFFF
Color7=0xFF0000FF
Color8=0xFFFA1BD0
Color9=0xFF7000FF
Color10=0xFF175B93
Color11=0xFF169F02
Color12=0xFFFF80FF
Color13=0xFFFF8080
Color14=0xFF808040
Color15=0xFFEA62C1
Color16=0xFF9D9DFF
Color17=0xFF808080
Color18=0xFFFF8040
Color19=0xFFAF0541

[HideMainDlgId]
//要在主界面隐藏的对话框ID
HideId=289,272,325,328,339,403,304,464,442
//还原时不需要恢复的对话框ID
NoResumeId=464,442

//竞技场形式的精英PK赛
[DlgElitePkGame]
EliteGameTimeGroup1=19:55-20:06
EliteGameTimeGroup2=19:55-20:04
EliteGameTimeGroup3=19:55-20:02
EliteGameTimeGroup4=19:55-20:00

//帮派对抗—帮派竞赛功能
[SynCompeteRank]
//与左边的距离
Left_1024=600
Left_800=300
//与上面的距离
Top=20
//每行的高度
Height=25
//名次与帮派名间隔50，帮派名与积分间隔150
Space=50,150

//帮派竞赛/帮派争霸赛奖赏的设置与分配
[CDlgSelfSynMemAwardRank]
//帮派成员奖赏界面时,取消按钮X轴的位置
BtnCancelX=150

[Skin]
//皮肤种类，没有正式资源，所配参数仅供参考
Amount=2

//飞鸽
[DlgPigeonQuery]
;发言者名字颜色(英雄自己)
HeroNameColor=0xFFFFFFFF
;发言者名字下划线颜色
LineColor=0xFF8080FF
;发言者编号颜色
OrderColor=0xFF008000
;发言加急点数颜色
PointColor=0xFFFF0000
;发言者名字(发言者是其他玩家)
SpeakerNameColor=0xFF000000

[Earthquake]
EffectOffset=200

//副本任务
[Ectype]
SmallIconX=465
SmallIconY=652
SmallIconX800x600=426
SmallIconY800x600=487

//外套试穿图标
[TryWrapTip]
TimeOffsetX=15
TimeOffsetY=15
FontSize=20
OffsetX=-5
OffsetY=-75

//组队PK赛
[DlgTeamPKRankQuery]
TEAMPKGameTimeGroup1=19:45-20:06
TEAMPKGameTimeGroup2=19:45-20:04
TEAMPKGameTimeGroup3=19:45-20:02
TEAMPKGameTimeGroup4=19:45-20:00

;屏幕中间提示的相关配置，这部分策划案并无描述具体样式，所有选项选配，不配置也能工作，可以视需要进行配置调整

[CenterMsg]
;中间提示的持续时间，选配，默认3000(ms)
TimeLast=3000
;无特定类型信息的颜色，选配，默认为0xffffff00
FontColor=0xffff00ff

[CenterMsgS]
;服务器提示类信息颜色，选配，默认为0xffff00ff
FontColor=0xffff00ff

[CenterMsgGUI1024]
;1024*768模式时的显示限宽，超过则折行显示
Width=300
[CenterMsgGUI800]
;800*600模式时的显示限宽，超过则折行显示
Width=300

// 更新公告中显示行数
[UpdateNotice]
LineCount=10

;记忆宝珠记忆点提示信息限制长度与语言版本相关
;中文版本下目前无需配置，默认20字节，10个汉字
[TeleportItem]
MaxRecordDescBytes=40

//表示连击数字显示的位置，以及3种连击数字的颜色和选取哪套光效资源
[HitNum]
x=600
y=100
Color1=0x880000fe
Color2=0xffffff00
Color3=0xffffffff
Res1=CountB
Res2=CountB
Res3=CountT

//MaxNum是最大掉血的目标   Rate是每个目标播放掉血光效的概率(0~10)为10就是每个光效都播放
[10415]   // 鹤翼xxx技能id
MaxNum=2
Rate=5

// 用于配置冷却提示的数字其位置大小和颜色
[SelectMagicNum]
OffsetX=0
OffsetY=0
FontSize=20
Color=0xffffff00

//组队PK赛
[DlgTeamPKRankQuery]
TEAMPKGameTimeGroup1=16:45-17:06
TEAMPKGameTimeGroup2=16:45-17:04
TEAMPKGameTimeGroup3=16:45-17:02
TEAMPKGameTimeGroup4=16:45-17:00

//帮派争霸赛前往参赛按钮的寻路
[WarFlagEntrance]
x=352
y=337
npc=380
radius=4

//组队大众PK赛
[DlgTeamPopPKRankQuery]
TEAMPKGameTimeGroup1=19:45-20:06
TEAMPKGameTimeGroup2=19:45-20:04
TEAMPKGameTimeGroup3=19:45-20:02
TEAMPKGameTimeGroup4=19:45-20:00

//南北互通客户端测速机制修改,建议不需要使用的时候先不配置，程序将读取默认配置80
[AccPercent]
AccountServer=80

//GM工具增加南北加速消息处理
//MiniDelay=200表示，若直连游服延迟低于200则直接直连，不进行BGP测速和连接
//AccPercent=80表示，若直连延迟为比BGP延迟高80以上，才使用BGP连接，例如BGP延迟为200，直连延迟大于 200*(100+80)%=360，方选择BGP连接
[BGP]
MiniDelay=200
AccPercent=80

//普通商店购买物品的样式修改
[MouseTip]
OffsetX=30
OffsetY=30
Width=500

// 用于配置当前技能冷却提示的数字其位置大小和颜色
[SelectMagicNum]
OffsetX=0
OffsetY=0
FontSize=20
Color=0xffffff00

// 用于配置快捷栏冷却时间数字其位置大小和颜色
[QuickMagicNum]
OffsetX=0
OffsetY=0
FontSize=20
Color=0xffffff00

//抽奖滚动一组物品图标的表现
[Lottery]
;滚动的总时间
LastingTime=2000
;每次实际参与滚动的图标个数，比如提供给某个抽奖npc，20个图标供滚动表现，每次只挑10参加滚动，这里就是指这个10
ApplyShow=10
;滚动时最多只能看到一个完整的图标或两个不完整的图标（不完整是指缺左边或缺右边）
VisableMax=1

//留言要求等级功能改由数据库配置,MinLev2other的值要和数据库配置的保持一致
[LeaveWord]
MinLev2other=70

//动态减面设置
[Simplify]
LowModeNum=10

[CrossFlagWar]
//地图id,x格子坐标,y格子坐标,npc的id,半径
Entrance=1002,350,339,8713,4

//招募信息字数限制
[FactionRecruit]
AdMaxShowSize=182

//人物界面里骑马效果配置
[QueryMission]
DummyZoomPercent=120
DummyOffsetX=100
DummyOffsetY=230
ArabicDummyOffsetX=100
ArabicDummyOffsetY=245

[NpcEquip]
DummyZoomPercent=120
DummyOffsetX=134
DummyOffsetY=310
ArabicDummyOffsetX=134
ArabicDummyOffsetY=310
