[CHEATING_PROGRAM_TIP]
Type=1
BgAniSection=Cheat_CheatBG
Mono=1
OkRect=100,110,40,19
TextRect=20,30,220,90
BoxRect=200,300,250,170

[Default452]
;换肤相关
BgAniSection=Dialog15
OkAniSection=Button150
CancelAniSection=Button151
;位置相关
OkRect=115,80,37,19
CancelRect=215,80,37,19
TextRect=10,10,265,17
BoxRect=365,300,290,108
BoxRect800X600=275,220,290,108
;结构相关
Type=3
;缩放相关
BoxBgZoom=0
;倒计时相关
CountDown=0
[TIP]
BgAniSection=Dialog15
OkAniSection=Button150
CancelAniSection=Button151
OkRect=115,67,37,19
CancelRect=215,67,37,19
TextRect=10,10,265,17
BoxRect=365,300,290,108
BoxRect800X600=275,220,290,108
Type=1
[FRIENDDEL_CONFIRM]
Type=3
[TALKDEL_CONFIRM]
Type=3
[FACTIONOUT_CONFIRM]
Type=3
[FACTIONDEL_CONFIRM]
Type=3
StrRes=10360
[BOOTHOPEN_CONFIRM]
Type=3
[IMPTITEM_CONFIRM]
Type=3
[DROPITEM_CONFIRM]
Type=3
StrRes=10372
[TACKOFF_CONFIRM]
Type=3
[JOINDICE_CONFIRM]
Type=3
[OUTDICE_CONFIRM]
Type=3
[ENEMYDEL_CONFIRM]
Type=3
[RESOURCE_CONFIRM]
Type=3
[EXPBALL_HALF_CONFIRM]
Type=3
[EXPBALL_RESULT_CONFIRM]
Type=3
StrRes=10490
[BLACKNAME_ADD_CONFIRM]
Type=3
StrRes=11017
[AUTORUN_CONFIRM]
Type=3
[BUYITEM_CONFIRM]
Type=3
Cn_Res=STR_BUY_ITEM_CONFIRM
[BUYSHADINESSGOOD_CONFIRM]
Type=3
StrRes=11164
[BETRAY_CONFIRM]
Type=3
[DELTRADEBUDDY_CONFIRM]
Type=3
StrRes=11146
[UNFAIRTRADE_CONFIRM]
Type=3
[DRUMOUT_CONFIRM]
Type=3
StrRes=100254
[BIND_CONFIRM]
Type=3
StrRes=11197
[UNBIND_CONFIRM]
Type=3
StrRes=11193
[REBIND_CONFIRM]
Type=3
[WITHDRAW_EMONEY_TIP]
Type=1
StrRes=11200
[MONOPOLY_CONFIRM]
Type=3
[EXIT_GAME_CONFIRM]
IDD=454
Type=3
StrRes=11000
[Default453]
BgAniSection=Dialog15
OkAniSection=Button150
CancelAniSection=Button151
Type=3
;邀请传送确认框，NumberOffsetX NumberOffsetY为数字光效倒计时相对于对话框的坐标
[INVITE_TRANS_CONFIRM]
IDD=453
NumberOffsetX=100
NumberOffsetY=-40

[Default456]
BgAniSection=Dialog15
OkAniSection=Button150
CancelAniSection=Button151
Type=3

[MPCCOURT_CONFIRM]
IDD=456
BgAniSection=Dialog45
OkRect=85,91,64,19
CancelRect=195,91,64,19
TextRect=60,70,265,17
TextTitleRect=40,26,150,17
TextLevRect=124,45,150,17

[TRADE_CONFIRM]
IDD=456
CountDown=10
Mono=1
StrRes_Mono=10433

[TEAM_CONFIRM]
IDD=456
CountDown=10

[FACTION_CONFIRM]
IDD=456

[APPLY_TRADEBUDDY_CONFIRM]
IDD=456


[MATE_TRADE_CONFIRM]
IDD=456
BgAniSection=MutualApply_MutualApplyBG
TextRect=85,110,265,17
TextTitleRect=75,67,150,17
TextLevRect=154,87,150,17
OkRect=115,150,64,19
CancelRect=215,150,64,19
BoxRect=365,300,400,216
BoxRect800X600=275,220,400,216
CountDown=10
Mono=1
StrRes_Mono=10433

[MATE_TEAM_CONFIRM]]
IDD=456
BgAniSection=MutualApply_MutualApplyBG
TextRect=85,110,265,17
TextTitleRect=75,67,150,17
TextLevRect=154,87,150,17
OkRect=115,150,64,19
CancelRect=215,150,64,19
BoxRect=365,300,400,216
BoxRect800X600=275,220,400,216
CountDown=10

[MATE_FACTION_CONFIRM]
IDD=456
BgAniSection=MutualApply_MutualApplyBG
TextRect=85,110,265,17
TextTitleRect=75,67,150,17
TextLevRect=154,87,150,17
OkRect=115,150,64,19
CancelRect=215,150,64,19
BoxRect=365,300,400,216
BoxRect800X600=275,220,400,216

[MATE_APPLY_TRADEBUDDY_CONFIRM]
IDD=456
BgAniSection=MutualApply_MutualApplyBG
TextRect=85,110,265,17
TextTitleRect=75,67,150,17
TextLevRect=154,87,150,17
OkRect=115,150,64,19
CancelRect=215,150,64,19
BoxRect=365,300,400,216
BoxRect800X600=275,220,400,216

[CONFIRM_QUALIFYING_BUYSCORE]
;换肤相关
BgAniSection=Dialog15
OkAniSection=Button150
CancelAniSection=Button151
;位置相关
OkRect=115,67,37,19
CancelRect=215,67,37,19
TextRect=10,10,265,17
BoxRect=365,300,290,108
BoxRect800X600=275,220,290,108
Type=3
;缩放相关
;BoxBgZoom=1
;ZoomWidth=300
;ZoomHeight=108
;倒计时相关
;CountDown=0

[CONFIRM_HONORSHOP_BUYITEM]
;换肤相关
BgAniSection=Dialog15
OkAniSection=Button150
CancelAniSection=Button151
;位置相关
OkRect=115,67,37,19
CancelRect=215,67,37,19
TextRect=10,10,265,17
BoxRect=365,300,290,108
BoxRect800X600=275,220,290,108
Type=3
;缩放相关
;BoxBgZoom=1
;ZoomWidth=300
;ZoomHeight=108
;倒计时相关
;CountDown=0

[CONFIRM_NPC_PROTECT]
IDD=453
CountDownStr=STR_PROTECTNPC_ACCEPT
NumberOffsetX=5
NumberOffsetY=-40
Cn_Res=STR_PROTECTNPC_QUEST

[CONFIRM_EQUIP_ACTIVE]
;换肤相关
BgAniSection=Dialog15
OkAniSection=Button150
CancelAniSection=Button151
;位置相关
OkRect=115,67,37,19
CancelRect=215,67,37,19
TextRect=10,10,265,17
BoxRect=365,300,290,108
BoxRect800X600=275,220,290,108
Type=3
;缩放相关
;BoxBgZoom=1
;ZoomWidth=300
;ZoomHeight=108
;倒计时相关
;CountDown=0

[CONFIRM_ITEM_ACTIVE]
;换肤相关
BgAniSection=Dialog15
OkAniSection=Button150
CancelAniSection=Button151
;位置相关
OkRect=115,67,37,19
CancelRect=215,67,37,19
TextRect=10,10,265,17
BoxRect=365,300,290,108
BoxRect800X600=275,220,290,108
Type=3
;缩放相关
;BoxBgZoom=1
;ZoomWidth=300
;ZoomHeight=108
;倒计时相关
;CountDown=0

[CONFIRM_EQUIP_HAS_QUENCH_STATUS]
;换肤相关
BgAniSection=Dialog15
OkAniSection=Button150
CancelAniSection=Button151
;位置相关
OkRect=115,67,37,19
CancelRect=215,67,37,19
TextRect=10,10,265,17
BoxRect=365,300,290,108
BoxRect800X600=275,220,290,108
Type=3
;缩放相关
;BoxBgZoom=1
;ZoomWidth=300
;ZoomHeight=108
;倒计时相关
;CountDown=0

[CONFIRM_EQUIP_HAS_SOLID_QUENCH_STATUS]
;换肤相关
BgAniSection=Dialog15
OkAniSection=Button150
CancelAniSection=Button151
;位置相关
OkRect=115,67,37,19
CancelRect=215,67,37,19
TextRect=10,10,265,17
BoxRect=365,300,290,108
BoxRect800X600=275,220,290,108
Type=3
;缩放相关
;BoxBgZoom=1
;ZoomWidth=300
;ZoomHeight=108
;倒计时相关
;CountDown=0

[CONFIRM_EQUIP_NO_QUENCH_STATUS]
;换肤相关
BgAniSection=Dialog15
OkAniSection=Button150
CancelAniSection=Button151
;位置相关
OkRect=115,67,37,19
CancelRect=215,67,37,19
TextRect=10,10,265,17
BoxRect=365,300,290,108
BoxRect800X600=275,220,290,108
Type=3
;缩放相关
;BoxBgZoom=1
;ZoomWidth=300
;ZoomHeight=108
;倒计时相关
;CountDown=0

[DROP_MONEY_CONFIRM]
IDD=457
Type=3

[MPCBOOTHADD_CONFIRM]
IDD=458
Type=3

[TIP]
IDD=452
Type=1
OkRect=115,67,37,19
CancelRect=215,67,37,19
TextRect=10,10,265,17
BoxRect=365,300,290,108
BoxRect800X600=275,220,290,108

[CONFIRM]
IDD=452
Type=3
OkRect=115,67,37,19
CancelRect=215,67,37,19
TextRect=10,10,265,17
BoxRect=365,300,290,108
BoxRect800X600=275,220,290,108

[OCCUPY_CHANENLLEGE]
IDD=452
Type=3
OkRect=115,67,37,19
CancelRect=215,67,37,19
TextRect=10,10,265,17
BoxRect=365,300,290,108
BoxRect800X600=275,220,290,108

[CHANLLEGE_MORE_CONFIRM]
IDD=452
Type=3
OkRect=115,67,37,19
CancelRect=215,67,37,19
TextRect=10,10,265,17
BoxRect=365,300,290,108
BoxRect800X600=275,220,290,108

[RIDEMATCH_RESULT]
Type=1
BgAniSection=Ride_CongratuBG
OkAniSection=Button555
OkRect=160,143,63,20
TextRect=70,75,230,62
BoxRect=300,250,350,173
BoxRect800X600=200,200,350,173

[QUALIFY_QUIT_CONFIRM]
Type=3

[ELITE_ROLE_TIP]
BgAniSection=Eliterace_RuleshowBG
OkAniSection=Eliterace_ReadedBtn
CancelAniSection=Button151
OkRect=345,185,62,20
CancelRect=215,67,64,19
TextRect=25,30,370,150
BoxRect=340,300,425,215
BoxRect800X600=200,220,425,215
Type=1

[INPUT_AWARD]
BgAniSection=Dialog15
OkAniSection=Button150
CancelAniSection=Button151
OkRect=115,67,37,19
CancelRect=215,67,37,19
TextRect=10,10,265,17
BoxRect=365,300,290,108
BoxRect800X600=275,220,290,108
Type=1

[TEXAS_IN_CONFIRM]
IDD=488
BgAniSection=NewSqu_JoinTipBG

[SH_ADVISE_CONFIRM]
IDD=499
;换肤相关
BgAniSection=Dialog15
OkAniSection=NewSqu_AdviceBtn
CancelAniSection=Squeezer_CancelBtn
;位置相关
OkRect=40,75,80,22
CancelRect=180,75,65,22
TextRect=10,10,265,17
BoxRect=365,300,290,108
BoxRect800X600=275,220,290,108
;结构相关
Type=3
;缩放相关
BoxBgZoom=0
;倒计时相关
CountDown=0
NeedBuffer=1

[SH_PRE_JOIN_TIP]

[SH_LEAVE_TABLE_CONFIRM]

[WRAPSHOP_BUY]
IDD=503

[EQUIP_DEGRADE_LOW_LEVEL_GOD_EQUIP_CONFIRM]
Type=3
Cn_Res=STR_EQUIP_DEGRADE_CONFIRM_LOW_LEVEL_GOD_EQUIP

[BUYITEM_MONEY_CONFIRM]
Type=3
Cn_Res=STR_BUY_ITEM_MONEY_CONFIRM

[SUPERFLAG_OVERLAPPING_CONFIRM]
Type=3
Cn_Res=STR_SUPERFLAG_CONFIRM_OVERLAPPING

[CONFIRM_VIP_TEAM_BACK]
IDD=453
BgAniSection=Vip_SendInviteBG
OkAniSection=Vip_AgreeBtn
CancelAniSection=Vip_RefuseBtn
TextRect=20,45,320,50
Cn_Res=STR_VIP_BACK_ASK
CountDownEffect=0
CountDownRect=240,77,265,50
CountDownStr=STR_VIP_BACK_COUNTDOWN
OkRect=95,90,64,19
CancelRect=200,90,64,19

[CONFIRM_VIP_TEAM_TRANSPORT]
IDD=453
BgAniSection=Vip_SendInviteBG
OkAniSection=Vip_AgreeBtn
CancelAniSection=Vip_RefuseBtn
TextRect=20,45,320,50
Cn_Res=STR_VIP_TRANSPORT_ASK
CountDownEffect=0
CountDownRect=240,77,265,50
CountDownStr=STR_VIP_TRANSPORT_COUNTDOWN
OkRect=95,90,64,19
CancelRect=200,90,64,19

[WARFLAG_RULE_TIP]
BgAniSection=Eliterace_RuleshowBG
OkAniSection=Eliterace_ReadedBtn
CancelAniSection=Button151
OkRect=345,185,62,20
CancelRect=215,67,64,19
TextRect=25,30,390,150
BoxRect=340,300,425,215
BoxRect800X600=200,220,425,215
Type=1

[CROSS_FLAG_WAR_RULE_TIP]
BgAniSection=Eliterace_RuleshowBG
OkAniSection=Eliterace_ReadedBtn
CancelAniSection=Button151
OkRect=345,185,62,20
CancelRect=215,67,64,19
TextRect=25,30,390,150
BoxRect=340,300,425,215
BoxRect800X600=200,220,425,215
Type=1

[CONFIRM_FACTION_RECRUIT_JOIN]
IDD=453
Cn_Res=STR_FACTION_RECRUIT_JOIN_CONFIRM

[CONFIRM_ISSUE_RECRUIT]
IDD=453
Cn_Res=STR_ISSUE_RECRUIT_CONFIRM

[CONFIRM_ISSUE_RECRUIT_FEE]
IDD=544
Type=3
OkAniSection=Faction_Confirm_sBtn
CancelAniSection=Faction_CancelBtn
BgAniSection=Faction_Affiche_FeeBG
EdtAniSection=Faction_Input_Field1Pic
Tip1CnRes=STR_ISSUE_RECRUIT_FEE_TIP1
Tip2CnRes=STR_ISSUE_RECRUIT_FEE_TIP2
Tip2Rect=14,74,200,70
DefaultEdtValue=500000
EdtValueMin=500000
EdtValueMax=4000000000
BoxRect=380,180,220,176
BoxRect800X600=300,130,220,176

[CONFIRM_ISSUE_RECRUIT_LEV]
IDD=544
Type=3
OkAniSection=Faction_Confirm_sBtn
CancelAniSection=Faction_CancelBtn
BgAniSection=Faction_Term_AmendBG
EdtAniSection=Faction_Input_Field2Pic
Tip1CnRes=STR_ISSUE_RECRUIT_LEV_TIP1
Tip2CnRes=STR_ISSUE_RECRUIT_LEV_TIP2
Tip2Rect=15,32,200,70
DefaultEdtValue=1
EdtValueMin=1
EdtValueMax=140
BoxRect=380,180,220,176
BoxRect800X600=300,130,220,176
OkRect=50,115,40,20
CancelRect=140,115,40,20
EdtRect=30,46,50,20

[CONFIRM_ISSUE_RECRUIT_REV]
IDD=544
Type=3
OkAniSection=Faction_Confirm_sBtn
CancelAniSection=Faction_CancelBtn
BgAniSection=Faction_Term_AmendBG
EdtAniSection=Faction_Input_Field2Pic
Tip2Rect=15,32,200,70
Tip1CnRes=STR_ISSUE_RECRUIT_REV_TIP1
Tip2CnRes=STR_ISSUE_RECRUIT_REV_TIP2
DefaultEdtValue=0
EdtValueMin=0
EdtValueMax=2
BoxRect=380,180,220,176
BoxRect800X600=300,130,220,176
OkRect=50,115,40,20
CancelRect=140,115,40,20
EdtRect=60,46,50,20
