<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="OpenConquer.Platform.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.Core" />
    <PackageReference Include="Silk.NET.Maths" />
    <PackageReference Include="Silk.NET.Windowing" />
  </ItemGroup>

</Project>
